import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });

// Public sign-up endpoint for hirers. Creates the email/password auth user and
// the hirers profile row with the service role, so the client never needs
// write access to auth or the hirers table. hirer_id is set by a DB trigger.
Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    );

    const body = await req.json();
    const firstName = String(body?.first_name ?? '').trim();
    const lastName = String(body?.last_name ?? '').trim();
    const mobile = String(body?.mobile_no ?? '').replace(/\D/g, '');
    const email = String(body?.email ?? '').trim().toLowerCase();
    const password = String(body?.password ?? '');

    // Validation (mirrors the client, enforced again server-side).
    if (!firstName || !lastName) {
      return json({ error: 'First and last name are required' }, 400);
    }
    if (mobile.length !== 10) {
      return json({ error: 'Enter a valid 10-digit mobile number' }, 400);
    }
    if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
      return json({ error: 'Enter a valid email address' }, 400);
    }
    if (password.length < 6) {
      return json({ error: 'Password must be at least 6 characters' }, 400);
    }

    // 1. Create the auth user (email pre-confirmed so they can sign in at once).
    const { data: created, error: createErr } = await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { role: 'hirer', first_name: firstName, last_name: lastName },
    });
    if (createErr || !created?.user) {
      const msg = (createErr?.message ?? '').toLowerCase();
      const already = msg.includes('already') || msg.includes('registered') || msg.includes('exists');
      return json(
        { error: already ? 'This email is already registered. Please sign in.' : (createErr?.message ?? 'Could not create account') },
        already ? 409 : 400,
      );
    }

    const userId = created.user.id;

    // 2. Insert the hirer profile (hirer_id auto-generated by the DB trigger).
    const { error: insertErr } = await supabaseAdmin.from('hirers').insert({
      first_name: firstName,
      last_name: lastName,
      mobile_no: mobile,
      email,
      auth_user_id: userId,
      status: 'pending',
    });
    if (insertErr) {
      // Roll back the auth user so the hirer can retry with clean state.
      await supabaseAdmin.auth.admin.deleteUser(userId);
      const m = insertErr.message ?? '';
      let friendly = 'Could not save your details. Please try again.';
      if (m.includes('hirers_mobile_no_key')) friendly = 'This mobile number is already registered.';
      else if (m.includes('hirers_email_key')) friendly = 'This email is already registered. Please sign in.';
      console.error('hirers insert failed:', m);
      return json({ error: friendly }, 409);
    }

    return json({ success: true });
  } catch (err) {
    console.error('hirer-signup error:', err?.message ?? err);
    return json({ error: 'Unexpected server error' }, 500);
  }
});
